### ISSUE TITLE
Physfs-rs relying on global state

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/physfs-rs#1]
https://github.com/PistonDevelopers/piston/issues/494#issuecomment-49662343

> On another note, I've found that PhysFS is implemented via a global state, which makes it very inconvenient if not impossible to instantiate multiple AssetStore objects that rely on PhysFS.

**Comment by cirla** [comment]
The `physfs::PhysFSContext` struct in this project is misleading by nature of being a struct. You cannot create two `PhysFSContext`s that operate independently of one another; calling `mount()` on one of them is like calling `mount()` on all of them (as @ghost mentioned, the PhysFS context is global/static). The `PhysFSContext` struct should be done away with and its methods moved into the module to make this clear.

Being able to use PhysFS to implement an `AssetStore`s is not very tractable as multiple `AssetStore`s need to function independently from one another.
